import { eq, and } from "drizzle-orm";
import { db } from "../index";
import { hrServices, InsertHrService } from "../schema";
import { log } from "../../utils/logger";

const data: InsertHrService[] = [
  // Automobile
  { name: "Senior Automotive Engineer", category: "Job Opportunities", industrySlug: "automobile", company: "Tata Motors", type: "Full-time", experience: "5-8 years", salary: "₹15-25 LPA", city: "Pune", rating: "4.8", skills: JSON.stringify(["Automotive Design", "CAD/CAM", "Lean Manufacturing", "Quality Control"]), description: "Lead automotive engineering projects for passenger vehicle development", isActive: true },
  { name: "Production Manager", category: "Job Opportunities", industrySlug: "automobile", company: "Maruti Suzuki", type: "Full-time", experience: "8-12 years", salary: "₹20-35 LPA", city: "Gurgaon", rating: "4.7", skills: JSON.stringify(["Production Planning", "Team Management", "Kaizen", "Six Sigma"]), description: "Oversee automotive production lines and optimize manufacturing processes", isActive: true },
  { name: "Automotive Talent Acquisition", category: "Recruitment Services", industrySlug: "automobile", company: "ManpowerGroup India", type: "Service", experience: "All levels", salary: "Commission based", city: "Chennai", rating: "4.6", skills: JSON.stringify(["Automotive Recruitment", "Industry Networks", "Technical Screening"]), description: "Specialized recruitment for automotive manufacturing and R&D roles", isActive: true },
  // Aerospace
  { name: "Aerospace Systems Engineer", category: "Job Opportunities", industrySlug: "aerospace", company: "Hindustan Aeronautics Limited", type: "Full-time", experience: "3-6 years", salary: "₹12-20 LPA", city: "Bangalore", rating: "4.9", skills: JSON.stringify(["Avionics", "Flight Systems", "Aerospace Materials", "Testing"]), description: "Design and develop aerospace systems for aircraft and helicopters", isActive: true },
  { name: "Flight Test Engineer", category: "Job Opportunities", industrySlug: "aerospace", company: "Bharat Dynamics Limited", type: "Full-time", experience: "4-8 years", salary: "₹18-28 LPA", city: "Hyderabad", rating: "4.8", skills: JSON.stringify(["Flight Testing", "Data Analysis", "Safety Protocols", "Instrumentation"]), description: "Conduct flight tests and analyze performance data for aerospace vehicles", isActive: true },
  { name: "Aerospace HR Consulting", category: "HR Consulting", industrySlug: "aerospace", company: "Aero Talent Solutions", type: "Consulting", experience: "Expert level", salary: "₹1.5-4 LPA", city: "Bangalore", rating: "4.7", skills: JSON.stringify(["Aerospace Industry Knowledge", "Security Clearance", "Technical Hiring"]), description: "Specialized HR consulting for aerospace and defense organizations", isActive: true },
  // Electronics
  { name: "Electronics Design Engineer", category: "Job Opportunities", industrySlug: "electronics", company: "Bharat Electronics Limited", type: "Full-time", experience: "2-5 years", salary: "₹8-15 LPA", city: "Bangalore", rating: "4.7", skills: JSON.stringify(["PCB Design", "Embedded Systems", "Signal Processing", "Testing"]), description: "Design electronic circuits and systems for defense and civilian applications", isActive: true },
  { name: "Firmware Engineer", category: "Job Opportunities", industrySlug: "electronics", company: "Wipro Technologies", type: "Full-time", experience: "3-7 years", salary: "₹12-22 LPA", city: "Pune", rating: "4.6", skills: JSON.stringify(["C/C++", "Microcontrollers", "RTOS", "Hardware Integration"]), description: "Develop firmware for electronic devices and embedded systems", isActive: true },
  { name: "Electronics Recruitment Services", category: "Recruitment Services", industrySlug: "electronics", company: "TechMahindra Recruitment", type: "Service", experience: "All levels", salary: "Commission based", city: "Hyderabad", rating: "4.5", skills: JSON.stringify(["Electronics Hiring", "Technical Assessment", "Industry Networks"]), description: "Comprehensive recruitment solutions for electronics and semiconductor companies", isActive: true },
  // Electric
  { name: "Electrical Systems Engineer", category: "Job Opportunities", industrySlug: "electric", company: "Power Grid Corporation", type: "Full-time", experience: "4-8 years", salary: "₹15-25 LPA", city: "Gurgaon", rating: "4.8", skills: JSON.stringify(["Power Systems", "Grid Integration", "Protection Systems", "SCADA"]), description: "Design and maintain electrical power distribution systems", isActive: true },
  { name: "EV Powertrain Engineer", category: "Job Opportunities", industrySlug: "electric", company: "Ola Electric", type: "Full-time", experience: "3-6 years", salary: "₹18-30 LPA", city: "Bangalore", rating: "4.9", skills: JSON.stringify(["Electric Motors", "Battery Systems", "Control Systems", "Charging"]), description: "Develop electric vehicle powertrain systems and charging solutions", isActive: true },
  { name: "Electrical Training Programs", category: "Training & Development", industrySlug: "electric", company: "Schneider Electric India", type: "Training", experience: "All levels", salary: "₹25,000-75,000", city: "Mumbai", rating: "4.7", skills: JSON.stringify(["Electrical Safety", "Automation", "Energy Management", "Digital Systems"]), description: "Comprehensive training programs for electrical professionals", isActive: true },
  // Medical
  { name: "Biomedical Engineer", category: "Job Opportunities", industrySlug: "medical", company: "Apollo Hospitals", type: "Full-time", experience: "3-6 years", salary: "₹12-18 LPA", city: "Chennai", rating: "4.8", skills: JSON.stringify(["Medical Devices", "FDA Regulations", "Quality Assurance", "Clinical Testing"]), description: "Design and develop medical devices and equipment for healthcare applications", isActive: true },
  { name: "Medical Device Quality Engineer", category: "Job Opportunities", industrySlug: "medical", company: "Siemens Healthcare", type: "Full-time", experience: "4-8 years", salary: "₹16-24 LPA", city: "Bangalore", rating: "4.7", skills: JSON.stringify(["ISO 13485", "Risk Management", "Design Controls", "Validation"]), description: "Ensure quality compliance for medical device manufacturing and testing", isActive: true },
  { name: "Healthcare Recruitment Specialists", category: "Recruitment Services", industrySlug: "medical", company: "MedTalent Solutions", type: "Service", experience: "All levels", salary: "Commission based", city: "Mumbai", rating: "4.6", skills: JSON.stringify(["Healthcare Recruitment", "Medical Regulations", "Compliance Hiring"]), description: "Specialized recruitment for medical device and healthcare organizations", isActive: true },
  // Space
  { name: "Satellite Systems Engineer", category: "Job Opportunities", industrySlug: "space", company: "ISRO", type: "Government", experience: "5-10 years", salary: "₹12-20 LPA", city: "Bangalore", rating: "5.0", skills: JSON.stringify(["Satellite Design", "Orbital Mechanics", "RF Systems", "Mission Analysis"]), description: "Design and develop satellite systems for space missions", isActive: true },
  { name: "Propulsion Engineer", category: "Job Opportunities", industrySlug: "space", company: "Agnikul Cosmos", type: "Full-time", experience: "3-7 years", salary: "₹15-25 LPA", city: "Chennai", rating: "4.9", skills: JSON.stringify(["Rocket Propulsion", "Fluid Dynamics", "Combustion", "Testing"]), description: "Develop propulsion systems for launch vehicles and spacecraft", isActive: true },
  { name: "Space Sector Payroll Services", category: "Payroll Services", industrySlug: "space", company: "Payroll Solutions India", type: "Service", experience: "All levels", salary: "Based on contract", city: "Bangalore", rating: "4.5", skills: JSON.stringify(["Payroll Processing", "Compliance", "Tax Management"]), description: "Specialized payroll and HR administration for space sector organizations", isActive: true },
  // Chemical
  { name: "Chemical Process Engineer", category: "Job Opportunities", industrySlug: "construction", company: "Reliance Industries", type: "Full-time", experience: "3-7 years", salary: "₹10-18 LPA", city: "Mumbai", rating: "4.7", skills: JSON.stringify(["Process Design", "Safety Management", "Chemical Engineering", "Quality Control"]), description: "Optimize chemical manufacturing processes for petrochemical plants", isActive: true },
  { name: "HSE Manager", category: "Job Opportunities", industrySlug: "construction", company: "BASF India", type: "Full-time", experience: "6-10 years", salary: "₹18-28 LPA", city: "Dahej", rating: "4.8", skills: JSON.stringify(["HAZOP", "Environmental Compliance", "Safety Audits", "ISO 45001"]), description: "Lead health, safety and environmental programs for chemical facilities", isActive: true },
  { name: "Chemical Industry HR Services", category: "HR Consulting", industrySlug: "construction", company: "Chem HR Professionals", type: "Consulting", experience: "All levels", salary: "Commission based", city: "Ahmedabad", rating: "4.5", skills: JSON.stringify(["Chemical Industry Hiring", "Compliance Screening", "Technical Assessment"]), description: "HR consulting and recruitment for chemical and pharma industries", isActive: true },
  // Pharma
  { name: "Pharmaceutical QA Manager", category: "Job Opportunities", industrySlug: "healthcare", company: "Sun Pharma", type: "Full-time", experience: "5-10 years", salary: "₹18-30 LPA", city: "Ahmedabad", rating: "4.9", skills: JSON.stringify(["GMP", "Quality Systems", "Regulatory Affairs", "Validation"]), description: "Lead quality assurance operations for pharmaceutical manufacturing", isActive: true },
  { name: "Regulatory Affairs Specialist", category: "Job Opportunities", industrySlug: "healthcare", company: "Dr. Reddy's Laboratories", type: "Full-time", experience: "4-8 years", salary: "₹15-22 LPA", city: "Hyderabad", rating: "4.8", skills: JSON.stringify(["USFDA Submissions", "CTD Dossier", "Global Regulatory Strategy", "WHO Guidelines"]), description: "Manage drug regulatory submissions for global markets", isActive: true },
  { name: "Pharma Compliance Management", category: "Compliance Management", industrySlug: "healthcare", company: "PharmaTalent", type: "Service", experience: "All levels", salary: "Based on contract", city: "Mumbai", rating: "4.7", skills: JSON.stringify(["GMP Compliance", "Audit Preparation", "FDA Guidance", "Risk Management"]), description: "Compliance management services for pharmaceutical companies", isActive: true },
];

export async function seedHrServices(): Promise<void> {
  log("Seeding HR services...");
  for (const item of data) {
    const [existing] = await db
      .select()
      .from(hrServices)
      .where(and(eq(hrServices.name, item.name), eq(hrServices.industrySlug, item.industrySlug!)));
    if (existing) { log(`  Already exists: ${item.name}`); continue; }
    await db.insert(hrServices).values(item);
    log(`  Created: ${item.name} (${item.industrySlug})`);
  }
  log(`HR services seeding complete. (${data.length} records)`);
}
