/**
 * Manufacturer Seeder
 *
 * Seeds the manufacturers table with capability-profile listings.
 * Includes generic sample manufacturers and Mohali industrial directory
 * entries adapted to the new schema (capabilities-focused, not directory).
 */

import { eq, and } from "drizzle-orm";
import { db } from "../index";
import { manufacturers, InsertManufacturer } from "../schema";
import { log } from "../../utils/logger";

const manufacturerData: InsertManufacturer[] = [
  // ── Generic capability profiles ──────────────────────────────────────────
  {
    industrySlug: "automobile",
    city: "Pune",
    state: "Maharashtra",
    totalEmployees: "500-1000",
    turnover: "₹80Cr - ₹400Cr",
    yearEstablished: "1995",
    certifications: JSON.stringify(["ISO 9001", "TS 16949", "CE"]),
    inHouseTesting: true,
    importExport: true,
    responseTime: "24 hours",
    rating: "4.8",
    machineCapabilities: JSON.stringify(["CNC Milling", "CNC Turning", "Wire EDM", "Surface Grinding"]),
    isActive: true,
  },
  {
    industrySlug: "aerospace",
    city: "Bangalore",
    state: "Karnataka",
    totalEmployees: "100-500",
    turnover: "₹40Cr - ₹80Cr",
    yearEstablished: "2005",
    certifications: JSON.stringify(["AS9100", "ISO 9001", "NADCAP"]),
    inHouseTesting: true,
    importExport: false,
    responseTime: "12 hours",
    rating: "4.9",
    machineCapabilities: JSON.stringify(["5-Axis CNC", "EDM", "CMM Inspection", "Heat Treatment"]),
    isActive: true,
  },
  {
    industrySlug: "electric",
    city: "Ahmedabad",
    state: "Gujarat",
    totalEmployees: "200-500",
    turnover: "₹160Cr - ₹400Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify(["ISO 9001", "BIS", "CE Mark"]),
    inHouseTesting: true,
    importExport: true,
    responseTime: "18 hours",
    rating: "4.7",
    machineCapabilities: JSON.stringify(["Winding", "Core Cutting", "Assembly", "Testing"]),
    isActive: true,
  },
  {
    industrySlug: "electronics",
    city: "Hyderabad",
    state: "Telangana",
    totalEmployees: "50-200",
    turnover: "₹16Cr - ₹40Cr",
    yearEstablished: "2010",
    certifications: JSON.stringify(["ISO 9001", "RoHS", "CE"]),
    inHouseTesting: true,
    importExport: false,
    responseTime: "24 hours",
    rating: "4.6",
    machineCapabilities: JSON.stringify(["PCB Assembly", "SMT", "Wave Soldering", "Testing"]),
    isActive: true,
  },
  {
    industrySlug: "construction",
    city: "Delhi",
    state: "Delhi NCR",
    totalEmployees: "200-500",
    turnover: "₹120Cr - ₹240Cr",
    yearEstablished: "1998",
    certifications: JSON.stringify(["ISO 9001", "ISI Mark", "BIS"]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.5",
    machineCapabilities: JSON.stringify(["Fabrication", "Welding", "Rolling", "Bending"]),
    isActive: true,
  },
  {
    industrySlug: "healthcare",
    city: "Mumbai",
    state: "Maharashtra",
    totalEmployees: "100-200",
    turnover: "₹40Cr - ₹120Cr",
    yearEstablished: "2003",
    certifications: JSON.stringify(["ISO 13485", "CE", "FDA"]),
    inHouseTesting: true,
    importExport: true,
    responseTime: "12 hours",
    rating: "4.8",
    machineCapabilities: JSON.stringify(["Precision Machining", "Clean Room Assembly", "Sterilization"]),
    isActive: true,
  },
  {
    industrySlug: "medical",
    city: "Coimbatore",
    state: "Tamil Nadu",
    totalEmployees: "50-100",
    turnover: "₹8Cr - ₹40Cr",
    yearEstablished: "2008",
    certifications: JSON.stringify(["ISO 13485", "CE Mark"]),
    inHouseTesting: true,
    importExport: false,
    responseTime: "24 hours",
    rating: "4.7",
    machineCapabilities: JSON.stringify(["Micro Machining", "Laser Cutting", "Anodizing"]),
    isActive: true,
  },

  // ── Mohali Industrial Directory (Phase IX) ────────────────────────────────
  // Sourced from Mohali MSME directory; adapted to capability-profile schema.
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["3M Tools and Components", "Tools and industrial components manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "electronics",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["A&S Technology", "Technology solutions and manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "electronics",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹5Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["A&N Technologies", "Technology products and solutions"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["A.G. Industries", "Industrial products and manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "electronics",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹5Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["A.K. Infotech", "IT solutions and technology services"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["A.P. Industion Centre", "Industrial solutions and manufacturing services"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Aaksu Industries", "Industrial products and components"]),
    isActive: true,
  },
  {
    industrySlug: "raw-materials",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "50-200",
    turnover: "₹5Cr - ₹50Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Aar Kay Deepak Steels (P) Ltd", "Steel products and wire manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "construction",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Aar Pary Glasses (P) Ltd", "Glass products and solutions"]),
    isActive: true,
  },
  {
    industrySlug: "raw-materials",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "50-200",
    turnover: "₹5Cr - ₹50Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify(["ISO 9001"]),
    inHouseTesting: false,
    importExport: true,
    responseTime: "48 hours",
    rating: "4.2",
    machineCapabilities: JSON.stringify(["Acro Polymers & Metallics", "Polymer and metallic products manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "healthcare",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "50-200",
    turnover: "₹5Cr - ₹50Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify(["ISO 13485"]),
    inHouseTesting: true,
    importExport: true,
    responseTime: "24 hours",
    rating: "4.3",
    machineCapabilities: JSON.stringify(["Adonis Medical Systems Pvt Ltd", "Medical systems and equipment manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Aey Kay Enterprises", "General manufacturing and trading"]),
    isActive: true,
  },
  {
    industrySlug: "raw-materials",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Agro Industries", "Agricultural equipment and solutions"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Ahluwalia Associates & Engg Products", "Engineering products and consulting"]),
    isActive: true,
  },
  {
    industrySlug: "raw-materials",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹5Cr - ₹50Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: true,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Ajay International", "International trading and manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "construction",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Akal Paper Moulding (P) Ltd", "Paper moulding and packaging solutions"]),
    isActive: true,
  },
  {
    industrySlug: "construction",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Akal Print Packs", "Printing and packaging solutions"]),
    isActive: true,
  },
  {
    industrySlug: "raw-materials",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "200-500",
    turnover: "₹50Cr - ₹200Cr",
    yearEstablished: "1990",
    certifications: JSON.stringify(["ISO 9001"]),
    inHouseTesting: true,
    importExport: true,
    responseTime: "24 hours",
    rating: "4.4",
    machineCapabilities: JSON.stringify(["Akzonobel India Ltd", "Paints, coatings and specialty chemicals"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Alfa Industries", "Industrial products and solutions"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "50-200",
    turnover: "₹5Cr - ₹50Cr",
    yearEstablished: "1995",
    certifications: JSON.stringify(["ISO 9001"]),
    inHouseTesting: true,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.2",
    machineCapabilities: JSON.stringify(["Allena Auto Industries (P) Ltd", "Automotive components and parts manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "electronics",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Alpha Net Technologies Pvt Ltd", "Technology solutions and networking"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Amar Engineering Works", "Engineering works and manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Amar Enterprises", "Trading and manufacturing services"]),
    isActive: true,
  },
  {
    industrySlug: "raw-materials",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹5Cr - ₹50Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: true,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Amfab International", "International trading and fabrication"]),
    isActive: true,
  },
  {
    industrySlug: "raw-materials",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Amitoj Polymers", "Polymer products and manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Ample Qualities", "Quality assurance and manufacturing services"]),
    isActive: true,
  },
  {
    industrySlug: "electric",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "50-200",
    turnover: "₹5Cr - ₹50Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify(["ISO 9001"]),
    inHouseTesting: true,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.1",
    machineCapabilities: JSON.stringify(["Amson Transformers", "Transformer manufacturing and electrical equipment"]),
    isActive: true,
  },
  {
    industrySlug: "electric",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "10-50",
    turnover: "₹1Cr - ₹10Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify([]),
    inHouseTesting: false,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.0",
    machineCapabilities: JSON.stringify(["Anand Electric Circuit", "Electrical circuits and components"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "50-200",
    turnover: "₹5Cr - ₹50Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify(["ISO 9001"]),
    inHouseTesting: true,
    importExport: false,
    responseTime: "48 hours",
    rating: "4.2",
    machineCapabilities: JSON.stringify(["Anantvir Auto Engg (P) Ltd", "Automotive engineering and manufacturing"]),
    isActive: true,
  },
  {
    industrySlug: "automobile",
    city: "Mohali",
    state: "Punjab",
    totalEmployees: "50-200",
    turnover: "₹5Cr - ₹50Cr",
    yearEstablished: "2000",
    certifications: JSON.stringify(["ISO 9001"]),
    inHouseTesting: true,
    importExport: true,
    responseTime: "24 hours",
    rating: "4.3",
    machineCapabilities: JSON.stringify(["Andel Equipment Pvt Ltd", "Industrial equipment manufacturing"]),
    isActive: true,
  },
];

export async function seedManufacturers(): Promise<void> {
  log("Seeding manufacturers...");

  for (const manufacturer of manufacturerData) {
    const capStr = manufacturer.machineCapabilities ?? "[]";
    const companyName = (JSON.parse(capStr) as string[])[0] ?? manufacturer.city;

    const existing = await db
      .select()
      .from(manufacturers)
      .where(
        and(
          eq(manufacturers.city, manufacturer.city),
          eq(manufacturers.machineCapabilities, capStr)
        )
      );

    if (existing.length > 0) {
      log(`  Already exists: ${companyName} (${manufacturer.city})`);
      continue;
    }

    await db.insert(manufacturers).values(manufacturer);
    log(`  Created: ${companyName} — ${manufacturer.industrySlug}, ${manufacturer.city}`);
  }

  log(`Manufacturers seeding complete. (${manufacturerData.length} records)`);
}
