/**
 * Raw Materials Seeder
 *
 * Seeds the raw_materials table with materials for multiple industries.
 */

import { eq, and } from "drizzle-orm";
import { db } from "../index";
import { rawMaterials, InsertRawMaterial } from "../schema";
import { log } from "../../utils/logger";

const rawMaterialData: InsertRawMaterial[] = [
  // ── Aerospace ────────────────────────────────────────────────────────────
  {
    industrySlug: "aerospace",
    name: "Aluminum 2024-T3 Sheet",
    category: "Aluminum",
    price: "₹285/kg",
    grade: "2024-T3",
    city: "Bangalore",
    imported: false,
    creditAvailable: true,
    quantity: "500 kg",
    rating: "4.8",
    description: "High-strength aluminum alloy sheet for aerospace structural components",
    specifications: JSON.stringify({ thickness: "0.5-6mm", width: "1000-2000mm", length: "2000-6000mm" }),
    certification: "ASTM B209",
    deliveryTime: "5-7 days",
    minOrder: "100 kg",
    isActive: true,
  },
  {
    industrySlug: "aerospace",
    name: "Titanium Ti-6Al-4V Grade 5 Plate",
    category: "Titanium",
    price: "₹3,850/kg",
    grade: "Grade 5",
    city: "Hyderabad",
    imported: true,
    creditAvailable: false,
    quantity: "200 kg",
    rating: "4.9",
    description: "Premium titanium alloy for high-temperature aerospace applications",
    specifications: JSON.stringify({ thickness: "1-50mm", width: "600-2000mm" }),
    certification: "AMS 4928",
    deliveryTime: "10-14 days",
    minOrder: "50 kg",
    isActive: true,
  },
  {
    industrySlug: "aerospace",
    name: "Carbon Fiber Prepreg CFRP",
    category: "Composites",
    price: "₹4,200/m²",
    grade: "T700",
    city: "Chennai",
    imported: true,
    creditAvailable: true,
    quantity: "100 m²",
    rating: "4.7",
    description: "Unidirectional carbon fiber prepreg for structural aerospace parts",
    specifications: JSON.stringify({ fiberOrientation: "0°/90°/±45°", thickness: "0.125mm/ply" }),
    certification: "Airbus AIMS 05-01-002",
    deliveryTime: "7-10 days",
    minOrder: "10 m²",
    isActive: true,
  },
  {
    industrySlug: "aerospace",
    name: "Inconel 718 Superalloy Bar",
    category: "Nickel Alloys",
    price: "₹2,950/kg",
    grade: "AMS 5663",
    city: "Mumbai",
    imported: true,
    creditAvailable: false,
    quantity: "300 kg",
    rating: "4.8",
    description: "Nickel-based superalloy for jet engine and high-temperature components",
    specifications: JSON.stringify({ diameter: "10-200mm", condition: "Solution Annealed + Aged" }),
    certification: "AMS 5663",
    deliveryTime: "14-21 days",
    minOrder: "25 kg",
    isActive: true,
  },
  {
    industrySlug: "aerospace",
    name: "Aluminum 7075-T651 Plate",
    category: "Aluminum",
    price: "₹320/kg",
    grade: "7075-T651",
    city: "Bhubaneswar",
    imported: false,
    creditAvailable: true,
    quantity: "1000 kg",
    rating: "4.6",
    description: "Aircraft-grade aluminum plate for fuselage and wing structures",
    specifications: JSON.stringify({ thickness: "3-100mm", temper: "T651" }),
    certification: "ASTM B209",
    deliveryTime: "3-5 days",
    minOrder: "100 kg",
    isActive: true,
  },
  {
    industrySlug: "aerospace",
    name: "17-4 PH Stainless Steel Rod",
    category: "Stainless Steel",
    price: "₹485/kg",
    grade: "17-4 PH",
    city: "Jajpur",
    imported: false,
    creditAvailable: true,
    quantity: "500 kg",
    rating: "4.7",
    description: "Precipitation hardening stainless steel for aerospace fasteners and fittings",
    specifications: JSON.stringify({ diameter: "6-100mm", condition: "H900" }),
    certification: "AMS 5643",
    deliveryTime: "5-7 days",
    minOrder: "50 kg",
    isActive: true,
  },
  // ── Automobile ───────────────────────────────────────────────────────────
  {
    industrySlug: "automobile",
    name: "SAE 1020 Mild Steel Sheet",
    category: "Steel & Alloys",
    price: "₹68/kg",
    grade: "SAE 1020",
    city: "Pune",
    imported: false,
    creditAvailable: true,
    quantity: "5000 kg",
    rating: "4.7",
    description: "Cold rolled mild steel sheet for automotive body panels",
    specifications: JSON.stringify({ thickness: "0.5-3mm", width: "1000-1500mm" }),
    certification: "IS 513",
    deliveryTime: "2-4 days",
    minOrder: "500 kg",
    isActive: true,
  },
  {
    industrySlug: "automobile",
    name: "Aluminum Alloy 6061-T6 Extrusion",
    category: "Aluminum",
    price: "₹220/kg",
    grade: "6061-T6",
    city: "Rajkot",
    imported: false,
    creditAvailable: true,
    quantity: "2000 kg",
    rating: "4.8",
    description: "Structural aluminum extrusion for chassis and structural components",
    specifications: JSON.stringify({ profile: "Custom", temper: "T6" }),
    certification: "IS 733",
    deliveryTime: "3-5 days",
    minOrder: "200 kg",
    isActive: true,
  },
  {
    industrySlug: "automobile",
    name: "EPDM Rubber Seal Strip",
    category: "Rubber & Elastomers",
    price: "₹185/m",
    grade: "EPDM 70 Shore A",
    city: "Mumbai",
    imported: false,
    creditAvailable: true,
    quantity: "1000 m",
    rating: "4.6",
    description: "Weather-resistant EPDM rubber seal for automotive doors and windows",
    specifications: JSON.stringify({ hardness: "70 Shore A", temperatureRange: "-40°C to 120°C" }),
    certification: "ASTM D2000",
    deliveryTime: "5-7 days",
    minOrder: "100 m",
    isActive: true,
  },
  {
    industrySlug: "automobile",
    name: "Polypropylene (PP) Granules",
    category: "Plastics & Polymers",
    price: "₹92/kg",
    grade: "PP-HH450FB",
    city: "Surat",
    imported: false,
    creditAvailable: true,
    quantity: "10000 kg",
    rating: "4.5",
    description: "High flow polypropylene for automotive interior injection molding",
    specifications: JSON.stringify({ MFI: "45 g/10min", density: "0.905 g/cm³" }),
    certification: "ISO 1133",
    deliveryTime: "2-3 days",
    minOrder: "1000 kg",
    isActive: true,
  },
  // ── Construction ─────────────────────────────────────────────────────────
  {
    industrySlug: "construction",
    name: "TMT Rebar Fe-500D",
    category: "Steel",
    price: "₹62/kg",
    grade: "Fe-500D",
    city: "Raipur",
    imported: false,
    creditAvailable: true,
    quantity: "50000 kg",
    rating: "4.8",
    description: "High ductility TMT rebar for earthquake-resistant construction",
    specifications: JSON.stringify({ diameter: "8-32mm", yieldStrength: "500 MPa" }),
    certification: "IS 1786",
    deliveryTime: "1-3 days",
    minOrder: "5000 kg",
    isActive: true,
  },
  {
    industrySlug: "construction",
    name: "Ordinary Portland Cement (OPC) 53",
    category: "Cement & Binders",
    price: "₹380/bag",
    grade: "OPC 53",
    city: "Delhi",
    imported: false,
    creditAvailable: false,
    quantity: "500 bags",
    rating: "4.7",
    description: "High-strength OPC cement for structural concrete applications",
    specifications: JSON.stringify({ bagSize: "50 kg", compressiveStrength: "53 MPa at 28 days" }),
    certification: "IS 12269",
    deliveryTime: "1-2 days",
    minOrder: "50 bags",
    isActive: true,
  },
  // ── Additional automobile materials (from GGI seed data) ─────────────────
  {
    industrySlug: "automobile",
    name: "High Carbon Steel AISI 1095",
    category: "Steel & Alloys",
    price: "₹290/kg",
    grade: "AISI 1095",
    city: "Pune",
    imported: false,
    creditAvailable: true,
    quantity: "500 kg",
    rating: "4.7",
    description: "Premium quality high carbon steel for automotive engine components",
    specifications: JSON.stringify({ tensileStrength: "620 MPa", density: "7.85 g/cm³", hardness: "HRC 45-50", composition: { iron: "98.1-98.9%", carbon: "0.90-1.03%", manganese: "0.25-0.40%" } }),
    certification: "ASTM A29",
    deliveryTime: "3-4 weeks",
    minOrder: "500 kg",
    isActive: true,
  },
  {
    industrySlug: "automobile",
    name: "Aluminum Alloy AA6061-T6 Sheet",
    category: "Aluminum",
    price: "₹500/kg",
    grade: "AA6061-T6",
    city: "Mumbai",
    imported: false,
    creditAvailable: true,
    quantity: "100 kg",
    rating: "4.8",
    description: "High-strength aluminum alloy sheet for automotive piston and structural applications",
    specifications: JSON.stringify({ tensileStrength: "310 MPa", density: "2.7 g/cm³", thermalConductivity: "167 W/m·K", composition: { aluminum: "95.8-98.6%", silicon: "0.4-0.8%", magnesium: "0.8-1.2%" } }),
    certification: "ASTM B209",
    deliveryTime: "2-3 weeks",
    minOrder: "100 kg",
    isActive: true,
  },
  // ── Electronics ──────────────────────────────────────────────────────────
  {
    industrySlug: "electronics",
    name: "FR4 PCB Laminate 1.6mm",
    category: "PCB Materials",
    price: "₹450/sheet",
    grade: "FR4 TG150",
    city: "Bangalore",
    imported: false,
    creditAvailable: true,
    quantity: "1000 sheets",
    rating: "4.7",
    description: "Standard FR4 fiberglass laminate for multi-layer PCB manufacturing",
    specifications: JSON.stringify({ thickness: "1.6mm", copperWeight: "35µm", size: "1020x1220mm" }),
    certification: "IPC-4101",
    deliveryTime: "3-5 days",
    minOrder: "100 sheets",
    isActive: true,
  },
  {
    industrySlug: "electronics",
    name: "Tin-Lead Solder Wire 60/40",
    category: "Soldering Materials",
    price: "₹680/kg",
    grade: "60Sn/40Pb",
    city: "Hyderabad",
    imported: false,
    creditAvailable: true,
    quantity: "500 kg",
    rating: "4.6",
    description: "Standard 60/40 solder wire for through-hole PCB assembly",
    specifications: JSON.stringify({ diameter: "0.8mm", flux: "2.2% No-Clean", meltingPoint: "183°C" }),
    certification: "IPC J-STD-006",
    deliveryTime: "2-4 days",
    minOrder: "10 kg",
    isActive: true,
  },
];

export async function seedRawMaterials(): Promise<void> {
  log("Seeding raw materials...");

  for (const material of rawMaterialData) {
    const [existing] = await db
      .select()
      .from(rawMaterials)
      .where(
        and(
          eq(rawMaterials.name, material.name),
          eq(rawMaterials.industrySlug, material.industrySlug)
        )
      );

    if (existing) {
      log(`  Raw material already exists: ${material.name}`);
      continue;
    }

    await db.insert(rawMaterials).values(material);
    log(`  Created raw material: ${material.name} (${material.industrySlug})`);
  }

  log(`Raw materials seeding complete. (${rawMaterialData.length} records)`);
}
